### ISSUE TITLE
[Docs] Add CI for static site generation

### ISSUE THREAD

**Issue by gabrielegenovese** [visimp/visimp#111]
I propose to use a static site generator like `mkdocs-material` or `docusaur` for a better experience in reading the documentation.

For example, adding this simple `mkdocs.yml`
```
site_name: Visimp docs 
theme:
  name: material
  palette:
    scheme: slate

plugins:
  - search
```
produce this result

![image](https://github.com/user-attachments/assets/c9ca9494-4807-4ac0-84e8-b7d4b9f6fef5)

[Mkdocs-material Github CI](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions-material-for-mkdocs)
